### ISSUE TITLE
Conflict with Minecolonies

### ISSUE THREAD

**Issue by nekoman09** [RebelliousUno/LavaSponge#102]
uno.rebellious.lavasponge.blocks.BlockRegister$1.getBurnTime(BlockRegister.java:30) ~[lavasponge-1.1.0-1.18.1.jar%23147!:1.1.0-1.18.1]

https://gist.github.com/nekoman09/5296f4ebce1cce4325525e0f9ad36a71

**Comment by RebelliousUno** [comment]
Thanks for raising.

Was there anything specific you were doing when this happened?

**Comment by RebelliousUno** [comment]
Fixed by 6c9c8aadc5ab407bb728da053a035b6381ae9ff6
